export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const FOCUS_CATEGORY = 'FOCUS_CATEGORY';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

export const DELETE_LOCATION = 'DELETE_LOCATION';
export const ADD_LOCATION = 'ADD_LOCATION';
export const EDIT_LOCATION = 'EDIT_LOCATION';
export const FOCUS_LOCATION = 'FOCUS_LOCATION';
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';

export const START_API_CALL = 'START_API_CALL';
export const FAIL_API_CALL = 'FAIL_API_CALL';



export const SORT_LOCATION_ALPHABETICALLY = 'SORT_LOCATION_ALPHABETICALLY';
export const SORT_LOCATION_CATEGORY = 'SORT_LOCATION_CATEGORY';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const CLEAR_ALL_FILTERS = 'CLEAR_ALL_FILTERS';


